package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/dinopuguh/gerr/cmd/gerr/spec"
)

// httpStatusNames maps every net/http status code constant to its Go identifier.
var httpStatusNames = map[int]string{
	// 1xx Informational
	http.StatusContinue:           "http.StatusContinue",
	http.StatusSwitchingProtocols: "http.StatusSwitchingProtocols",
	http.StatusProcessing:         "http.StatusProcessing",
	http.StatusEarlyHints:         "http.StatusEarlyHints",
	// 2xx Success
	http.StatusOK:                   "http.StatusOK",
	http.StatusCreated:              "http.StatusCreated",
	http.StatusAccepted:             "http.StatusAccepted",
	http.StatusNonAuthoritativeInfo: "http.StatusNonAuthoritativeInfo",
	http.StatusNoContent:            "http.StatusNoContent",
	http.StatusResetContent:         "http.StatusResetContent",
	http.StatusPartialContent:       "http.StatusPartialContent",
	http.StatusMultiStatus:          "http.StatusMultiStatus",
	http.StatusAlreadyReported:      "http.StatusAlreadyReported",
	http.StatusIMUsed:               "http.StatusIMUsed",
	// 3xx Redirection
	http.StatusMultipleChoices:   "http.StatusMultipleChoices",
	http.StatusMovedPermanently:  "http.StatusMovedPermanently",
	http.StatusFound:             "http.StatusFound",
	http.StatusSeeOther:          "http.StatusSeeOther",
	http.StatusNotModified:       "http.StatusNotModified",
	http.StatusUseProxy:          "http.StatusUseProxy",
	http.StatusTemporaryRedirect: "http.StatusTemporaryRedirect",
	http.StatusPermanentRedirect: "http.StatusPermanentRedirect",
	// 4xx Client Errors
	http.StatusBadRequest:                   "http.StatusBadRequest",
	http.StatusUnauthorized:                 "http.StatusUnauthorized",
	http.StatusPaymentRequired:              "http.StatusPaymentRequired",
	http.StatusForbidden:                    "http.StatusForbidden",
	http.StatusNotFound:                     "http.StatusNotFound",
	http.StatusMethodNotAllowed:             "http.StatusMethodNotAllowed",
	http.StatusNotAcceptable:                "http.StatusNotAcceptable",
	http.StatusProxyAuthRequired:            "http.StatusProxyAuthRequired",
	http.StatusRequestTimeout:               "http.StatusRequestTimeout",
	http.StatusConflict:                     "http.StatusConflict",
	http.StatusGone:                         "http.StatusGone",
	http.StatusLengthRequired:               "http.StatusLengthRequired",
	http.StatusPreconditionFailed:           "http.StatusPreconditionFailed",
	http.StatusRequestEntityTooLarge:        "http.StatusRequestEntityTooLarge",
	http.StatusRequestURITooLong:            "http.StatusRequestURITooLong",
	http.StatusUnsupportedMediaType:         "http.StatusUnsupportedMediaType",
	http.StatusRequestedRangeNotSatisfiable: "http.StatusRequestedRangeNotSatisfiable",
	http.StatusExpectationFailed:            "http.StatusExpectationFailed",
	http.StatusTeapot:                       "http.StatusTeapot",
	http.StatusMisdirectedRequest:           "http.StatusMisdirectedRequest",
	http.StatusUnprocessableEntity:          "http.StatusUnprocessableEntity",
	http.StatusLocked:                       "http.StatusLocked",
	http.StatusFailedDependency:             "http.StatusFailedDependency",
	http.StatusTooEarly:                     "http.StatusTooEarly",
	http.StatusUpgradeRequired:              "http.StatusUpgradeRequired",
	http.StatusPreconditionRequired:         "http.StatusPreconditionRequired",
	http.StatusTooManyRequests:              "http.StatusTooManyRequests",
	http.StatusRequestHeaderFieldsTooLarge:  "http.StatusRequestHeaderFieldsTooLarge",
	http.StatusUnavailableForLegalReasons:   "http.StatusUnavailableForLegalReasons",
	// 5xx Server Errors
	http.StatusInternalServerError:           "http.StatusInternalServerError",
	http.StatusNotImplemented:                "http.StatusNotImplemented",
	http.StatusBadGateway:                    "http.StatusBadGateway",
	http.StatusServiceUnavailable:            "http.StatusServiceUnavailable",
	http.StatusGatewayTimeout:                "http.StatusGatewayTimeout",
	http.StatusHTTPVersionNotSupported:       "http.StatusHTTPVersionNotSupported",
	http.StatusVariantAlsoNegotiates:         "http.StatusVariantAlsoNegotiates",
	http.StatusInsufficientStorage:           "http.StatusInsufficientStorage",
	http.StatusLoopDetected:                  "http.StatusLoopDetected",
	http.StatusNotExtended:                   "http.StatusNotExtended",
	http.StatusNetworkAuthenticationRequired: "http.StatusNetworkAuthenticationRequired",
}

const goTmpl = `// Code generated by gerr gen from {{ .SchemaFile }}. DO NOT EDIT.
package {{ .Schema.Package }}

import (
	"net/http"

	"github.com/dinopuguh/gerr"
)

// Error code constants.
const (
{{ range .Schema.Errors -}}
	Code{{ .Name }} = "{{ .Code }}"
{{ end -}}
)
{{ range .Schema.Errors }}
// {{ .Name }} creates a {{ .Key }} error.
func {{ .Name }}({{ argsParam .Args }}opts ...gerr.Option) error {
	return gerr.New(
		Code{{ .Name }},
		"{{ .Key }}",
		{{ httpStatus .HTTP }},
		{{ if .Args -}}
		append([]gerr.Option{gerr.WithArgs(map[string]any{ {{ argsMap .Args }} })}, opts...)...,
		{{- else -}}
		opts...,
		{{- end }}
	)
}
{{ end }}`

// GoGenerator implements spec.Generator for the Go language.
type Go struct{}

func (g *Go) Lang() string { return "go" }

func (g *Go) Generate(schema spec.Schema, opts spec.GenOptions) error {
	return g.generateGoFile(schema, opts)
}

func (g *Go) generateGoFile(schema spec.Schema, opts spec.GenOptions) error {
	funcMap := template.FuncMap{
		"httpStatus": func(code int) string {
			if name, ok := httpStatusNames[code]; ok {
				return name
			}
			return fmt.Sprintf("%d", code)
		},
		"argsParam": func(args []string) string {
			if len(args) == 0 {
				return ""
			}
			parts := make([]string, len(args))
			for i, a := range args {
				parts[i] = a + " string"
			}
			return strings.Join(parts, ", ") + ", "
		},
		"argsMap": func(args []string) string {
			parts := make([]string, len(args))
			for i, a := range args {
				parts[i] = fmt.Sprintf(`"%s": %s`, a, a)
			}
			return strings.Join(parts, ", ")
		},
	}

	tmpl, err := template.New("go").Funcs(funcMap).Parse(goTmpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]any{
		"Schema":     schema,
		"SchemaFile": filepath.Base(opts.SchemaFile),
	}); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		_ = os.WriteFile("gerr_gen_debug.go", buf.Bytes(), 0644)
		return fmt.Errorf("format generated code: %w (unformatted written to gerr_gen_debug.go)", err)
	}

	if err := os.MkdirAll(opts.OutDir, 0755); err != nil {
		return err
	}

	outName := strings.TrimSuffix(filepath.Base(opts.SchemaFile), ".yaml") + ".go"
	outPath := filepath.Join(opts.OutDir, outName)
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		return err
	}

	fmt.Printf("gerr gen: wrote %s\n", outPath)
	return nil
}
