package codegen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/dinopuguh/gerr/cmd/gerr/spec"
)

const tsTmpl = `// Code generated by gerr gen from {{ .SchemaFile }}. DO NOT EDIT.

export interface GerrError {
  code: string;
  messageKey: string;
  httpStatus: number;
  args?: Record<string, unknown>;
}

function newError(
  code: string,
  messageKey: string,
  httpStatus: number,
  args?: Record<string, unknown>,
): GerrError {
  return { code, messageKey, httpStatus, ...(args !== undefined ? { args } : {}) };
}

// Error code constants.
export const Codes = {
{{ range .Schema.Errors -}}
  {{ .Name }}: "{{ .Code }}",
{{ end -}}
} as const;
{{ range .Schema.Errors }}
// {{ .Name }} creates a {{ .Key }} error.
export function {{ .Name }}({{ argsParam .Args }}): GerrError {
  return newError(Codes.{{ .Name }}, "{{ .Key }}", {{ .HTTP }}{{ if .Args }}, { {{ argsObj .Args }} }{{ end }});
}
{{ end }}`

// TypeScriptGenerator implements spec.Generator for TypeScript.
type TypeScript struct{}

func (g *TypeScript) Lang() string { return "typescript" }

func (g *TypeScript) Generate(schema spec.Schema, opts spec.GenOptions) error {
	return g.generateTSFile(schema, opts)
}

func (g *TypeScript) generateTSFile(schema spec.Schema, opts spec.GenOptions) error {
	funcMap := template.FuncMap{
		"argsParam": func(args []string) string {
			if len(args) == 0 {
				return ""
			}
			parts := make([]string, len(args))
			for i, a := range args {
				parts[i] = a + ": string"
			}
			return strings.Join(parts, ", ")
		},
		"argsObj": func(args []string) string {
			parts := make([]string, len(args))
			for i, a := range args {
				parts[i] = a
			}
			return strings.Join(parts, ", ")
		},
	}

	tmpl, err := template.New("typescript").Funcs(funcMap).Parse(tsTmpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]any{
		"Schema":     schema,
		"SchemaFile": filepath.Base(opts.SchemaFile),
	}); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	if err := os.MkdirAll(opts.OutDir, 0755); err != nil {
		return err
	}

	outName := strings.TrimSuffix(filepath.Base(opts.SchemaFile), ".yaml") + ".ts"
	outPath := filepath.Join(opts.OutDir, outName)
	if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
		return err
	}

	fmt.Printf("gerr gen: wrote %s\n", outPath)
	return nil
}
